repo:
  scanPath: /var/www/git
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: icy does git
  description: come get your free software
server:
  name: git.icyphox.sh
  host: 0.0.0.0
  port: 5555
